### ISSUE TITLE
Configuration error

### ISSUE THREAD

**Issue by veritazx** [collective/collective.upgrade#11]
Version 1.6 has a configuration error that prevents startup:
zope.configuration.exceptions.ConfigurationError: Invalid value for 'handler'
...
    File ".../zinstance/eggs/collective.upgrade-1.6-py2.7.egg/collective/upgrade/resourceregistries.zcml", line 6.2
    ValidationError: ImportError: Module collective.upgrade.steps has no global importBBBCSSRegistry

**Comment by pgrunewald** [comment]
I added a PR for this issue. For completeness sake I added the full traceback. But eventually it traces back to the import error. It was easy to spot & fix. :)

<details>
  <summary>Click for traceback</summary>

```
Installing site.
WARNING:plone.behavior:Specifying 'for' in behavior 'Social Media' if no 'factory' is given has no effect and is superfluous.
Traceback (most recent call last):
  File "/home/user/plone/parts/instance/bin/interpreter", line 406, in <module>
    exec(_val)
  File "<string>", line 1, in <module>
  File "/home/user/plone/eggs/Zope-4.6.3-py2.7.egg/Zope2/__init__.py", line 55, in app
    startup_wsgi()
  File "/home/user/plone/eggs/Zope-4.6.3-py2.7.egg/Zope2/__init__.py", line 50, in startup_wsgi
    _startup()
  File "/home/user/plone/eggs/Zope-4.6.3-py2.7.egg/Zope2/App/startup.py", line 143, in startup
    load_zcml()
  File "/home/user/plone/eggs/Zope-4.6.3-py2.7.egg/Zope2/App/startup.py", line 58, in load_zcml
    load_site()
  File "/home/user/plone/eggs/Zope-4.6.3-py2.7.egg/Zope2/App/zcml.py", line 45, in load_site
    _context = xmlconfig.file(site_zcml)
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 657, in file
    include(context, name, package)
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 557, in include
    processxmlfile(f, context)
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 407, in processxmlfile
    parser.parse(src)
  File "/usr/lib64/python2.7/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib64/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib64/python2.7/xml/sax/expatreader.py", line 220, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib64/python2.7/xml/sax/expatreader.py", line 384, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 393, in endElementNS
    self._handle_exception(ex, info)
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 391, in endElementNS
    self.context.end()
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/config.py", line 704, in end
    self.stack.pop().finish()
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/config.py", line 869, in finish
    actions = self.handler(context, **args)
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 557, in include
    processxmlfile(f, context)
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 407, in processxmlfile
    parser.parse(src)
  File "/usr/lib64/python2.7/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib64/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib64/python2.7/xml/sax/expatreader.py", line 220, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib64/python2.7/xml/sax/expatreader.py", line 384, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 393, in endElementNS
    self._handle_exception(ex, info)
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 391, in endElementNS
    self.context.end()
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/config.py", line 704, in end
    self.stack.pop().finish()
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/config.py", line 869, in finish
    actions = self.handler(context, **args)
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 557, in include
    processxmlfile(f, context)
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 407, in processxmlfile
    parser.parse(src)
  File "/usr/lib64/python2.7/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib64/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib64/python2.7/xml/sax/expatreader.py", line 220, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib64/python2.7/xml/sax/expatreader.py", line 384, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 393, in endElementNS
    self._handle_exception(ex, info)
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 391, in endElementNS
    self.context.end()
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/config.py", line 704, in end
    self.stack.pop().finish()
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/config.py", line 869, in finish
    actions = self.handler(context, **args)
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 557, in include
    processxmlfile(f, context)
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 407, in processxmlfile
    parser.parse(src)
  File "/usr/lib64/python2.7/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib64/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib64/python2.7/xml/sax/expatreader.py", line 220, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib64/python2.7/xml/sax/expatreader.py", line 384, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 393, in endElementNS
    self._handle_exception(ex, info)
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 391, in endElementNS
    self.context.end()
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/config.py", line 704, in end
    self.stack.pop().finish()
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/config.py", line 869, in finish
    actions = self.handler(context, **args)
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 557, in include
    processxmlfile(f, context)
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 407, in processxmlfile
    parser.parse(src)
  File "/usr/lib64/python2.7/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib64/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib64/python2.7/xml/sax/expatreader.py", line 220, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib64/python2.7/xml/sax/expatreader.py", line 384, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 393, in endElementNS
    self._handle_exception(ex, info)
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 391, in endElementNS
    self.context.end()
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/config.py", line 704, in end
    self.stack.pop().finish()
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/config.py", line 869, in finish
    actions = self.handler(context, **args)
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 557, in include
    processxmlfile(f, context)
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 407, in processxmlfile
    parser.parse(src)
  File "/usr/lib64/python2.7/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib64/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib64/python2.7/xml/sax/expatreader.py", line 220, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib64/python2.7/xml/sax/expatreader.py", line 384, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 393, in endElementNS
    self._handle_exception(ex, info)
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 391, in endElementNS
    self.context.end()
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/config.py", line 704, in end
    self.stack.pop().finish()
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/config.py", line 869, in finish
    actions = self.handler(context, **args)
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 557, in include
    processxmlfile(f, context)
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 407, in processxmlfile
    parser.parse(src)
  File "/usr/lib64/python2.7/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib64/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib64/python2.7/xml/sax/expatreader.py", line 220, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib64/python2.7/xml/sax/expatreader.py", line 384, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 393, in endElementNS
    self._handle_exception(ex, info)
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 391, in endElementNS
    self.context.end()
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/config.py", line 704, in end
    self.stack.pop().finish()
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/config.py", line 869, in finish
    actions = self.handler(context, **args)
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 557, in include
    processxmlfile(f, context)
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 407, in processxmlfile
    parser.parse(src)
  File "/usr/lib64/python2.7/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib64/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib64/python2.7/xml/sax/expatreader.py", line 220, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib64/python2.7/xml/sax/expatreader.py", line 384, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 393, in endElementNS
    self._handle_exception(ex, info)
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 391, in endElementNS
    self.context.end()
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/config.py", line 704, in end
    self.stack.pop().finish()
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/config.py", line 869, in finish
    actions = self.handler(context, **args)
  File "/home/user/plone/eggs/z3c.autoinclude-0.4.1-py2.7.egg/z3c/autoinclude/zcml.py", line 122, in includePluginsDirective
    includeZCMLGroup(_context, info, filename)
  File "/home/user/plone/eggs/z3c.autoinclude-0.4.1-py2.7.egg/z3c/autoinclude/zcml.py", line 37, in includeZCMLGroup
    include(_context, filename, includable_package)
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 557, in include
    processxmlfile(f, context)
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 407, in processxmlfile
    parser.parse(src)
  File "/usr/lib64/python2.7/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib64/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib64/python2.7/xml/sax/expatreader.py", line 220, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib64/python2.7/xml/sax/expatreader.py", line 384, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 393, in endElementNS
    self._handle_exception(ex, info)
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 391, in endElementNS
    self.context.end()
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/config.py", line 704, in end
    self.stack.pop().finish()
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/config.py", line 869, in finish
    actions = self.handler(context, **args)
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 557, in include
    processxmlfile(f, context)
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 407, in processxmlfile
    parser.parse(src)
  File "/usr/lib64/python2.7/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib64/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib64/python2.7/xml/sax/expatreader.py", line 220, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib64/python2.7/xml/sax/expatreader.py", line 384, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 393, in endElementNS
    self._handle_exception(ex, info)
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 391, in endElementNS
    self.context.end()
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/config.py", line 704, in end
    self.stack.pop().finish()
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/config.py", line 869, in finish
    actions = self.handler(context, **args)
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 557, in include
    processxmlfile(f, context)
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 407, in processxmlfile
    parser.parse(src)
  File "/usr/lib64/python2.7/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib64/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib64/python2.7/xml/sax/expatreader.py", line 220, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib64/python2.7/xml/sax/expatreader.py", line 373, in start_element_ns
    AttributesNSImpl(newattrs, qnames))
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 268, in startElementNS
    self._handle_exception(ex, info)
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 266, in startElementNS
    self.context.begin(name, data, info)
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/config.py", line 701, in begin
    self.stack.append(self.stack[-1].contained(__name, __data, __info))
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/config.py", line 1071, in contained
    return RootStackItem.contained(self, name, data, info)
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/config.py", line 895, in contained
    adapter = factory(self.context, data, info)
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/config.py", line 1508, in factory
    return ComplexStackItem(self, context, data, info)
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/config.py", line 1225, in __init__
    args = toargs(newcontext, meta.schema, data)
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/config.py", line 1690, in toargs
    None, sys.exc_info()[2])
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/config.py", line 1687, in toargs
    args[str(name)] = field.fromUnicode(s)
  File "/home/user/plone/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/fields.py", line 174, in fromUnicode
    raise ValidationError(v).with_field_and_value(self, name)
zope.configuration.exceptions.ConfigurationError: Invalid value for 'handler'
    File "/home/user/plone/parts/instance/etc/site.zcml", line 15.2-15.55
    File "/home/user/plone/parts/instance/etc/package-includes/002-tud.addons.webcms-configure.zcml", line 1.0-1.61
    File "/home/user/plone/src/tud.addons.webcms/tud/addons/webcms/configure.zcml", line 28.4-28.51
    File "/home/user/plone/src/collective.workspace/src/collective/workspace/configure.zcml", line 13.2-13.43
    File "/home/user/plone/eggs/plone.app.dexterity-2.6.10-py2.7.egg/plone/app/dexterity/configure.zcml", line 11.2-11.41
    File "/home/user/plone/eggs/plone.app.z3cform-3.2.3-py2.7.egg/plone/app/z3cform/configure.zcml", line 10.2-10.41
    File "/home/user/plone/eggs/plone.app.widgets-3.0.6-py2.7.egg/plone/app/widgets/configure.zcml", line 6.2-6.41
    File "/home/user/plone/eggs/Products.CMFPlone-5.2.7-py2.7.egg/Products/CMFPlone/configure.zcml", line 110.2-114.8
    File "/home/user/plone/eggs/collective.upgrade-1.7-py2.7.egg/collective/upgrade/configure.zcml", line 4.2-4.31
    File "/home/user/plone/eggs/collective.upgrade-1.7-py2.7.egg/collective/upgrade/steps.zcml", line 53.2-55.39
    File "/home/user/plone/eggs/collective.upgrade-1.7-py2.7.egg/collective/upgrade/resourceregistries.zcml", line 6.2
    ValidationError: ImportError: Module collective.upgrade.steps has no global importBBBCSSRegistry
```
</details>
